plugins {
    id 'java-library'
    id 'maven-publish'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

group = 'com.github.ja3kci'
version = '1.0.0'

repositories {
    mavenCentral()

    maven {url = "https://repo.papermc.io/repository/maven-public/"}
}
//
dependencies {
    compileOnly("io.papermc.paper:paper-api:1.21.4-R0.1-SNAPSHOT")
}

test {
    useJUnitPlatform()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            groupId = project.group
            artifactId = 'jlib'
            version = project.version
        }
    }
}